import { createElement } from 'lwc';
import OpportunitySearchWithDebouncingAndServerSideFetching from 'c/opportunitySearchWithDebouncingAndServerSideFetching';

describe('c-opportunity-search-with-debouncing-and-server-side-fetching', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-opportunity-search-with-debouncing-and-server-side-fetching', {
            is: OpportunitySearchWithDebouncingAndServerSideFetching
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});